class Classname:
    #some functions and variables
    #function-used to perform the specific activity
    #variables--Data(memory)

In [11]:
def test():
    return
test()

In [30]:
class Demo:
    def test(self):
        print("test() for the class and method")
        return
obj=Demo()
obj.test()

test() for the class and method


In [32]:
class Demo:
    def test():
        print("test() for the class and method")
        return
Demo.test()

test() for the class and method


In [20]:
class Demo1:
    def fact(self,n):
        #return the factorial
        fact=1
        while(n!=0):
            fact=fact*n
            n=n-1
        return fact
p1=Demo1()
print(p1.fact(5))#120

120


In [31]:
class Demo2:
    a=0
    b=0
    def Accept(self,p1,p2):
        self.a=p1
        self.b=p2
        return
    def display(self):
        print("a= ",self.a)
        print("b= ",self.b)
c1=Demo2()
c1.Accept(10,20)
c1.display()

a=  10
b=  20


In [51]:
class Demo2:
    def __init__(self,p1,p2):
        self.p1=p2
        self.p2=p1
    def add(self,p1,p2):
        return p1+p2
c1=Demo2(10,20)
print(c1.add(100,200))

TypeError: add() missing 2 required positional arguments: 'p1' and 'p2'

In [59]:
#Some inheritance
class Person():
    #Constructor
    def __init__(self,name):
        self.name=name
    def getName(self):
        return self.name
    def firstemployee(self):
        return false
#Derived class 
class employee(Person):
    def isemployee(self):
        return True
emp=Person("Anil")
print(emp.getName(),emp.isemployee())
emp1=employee("Akhil")
print(emp1.getName(),emp1.isemployee())

AttributeError: 'Person' object has no attribute 'isemployee'

### Phython Numpy
NumPy python is a bit like python list.
NumPy python is a central data structure of the numpy lib.
This lib actually short for 'Numeric Python' or 'Numerical Python'

In [60]:
lst=[1,2,3,4]
print(lst)

[1, 2, 3, 4]


In [61]:
import numpy as np
lst=[1,2,3,4]
array=np.array(lst)
print(array)

[1 2 3 4]


In [62]:
lst=[1,2,3,4]
array=np.array(lst)
print(array.shape)
print(array.dtype)


(4,)
int32


In [85]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1.shape)
a2=np.array([(1,2),(3,4),(5,6)])
print(a2.shape)

(2, 3)
(3, 2)


In [84]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1)
a1.reshape(3,2)

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [89]:
a1=np.array((1,2,3))
a2=np.array((4,5,6))
print(np.hstack((a1,a2)))

[1 2 3 4 5 6]


In [90]:
a1=np.array((1,2,3))
a2=np.array((4,5,6))
print(np.vstack((a1,a2)))

[[1 2 3]
 [4 5 6]]


In [97]:
a1=np.random.normal(5,0.5,10)
print(a1)

[4.61372443 4.75808269 5.81717717 4.52662322 5.4088416  5.21040351
 4.30395476 4.9261648  4.54849816 4.43459395]


In [98]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [99]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [102]:
A=np.matrix(np.ones((4,4)),dtype=np.int64)
print(A)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [104]:
A=np.matrix(np.ones((4,4)),dtype=np.int64)
np.asarray(A)[2]=5
print(A)

[[1 1 1 1]
 [1 1 1 1]
 [5 5 5 5]
 [1 1 1 1]]


In [105]:
A=np.matrix(np.ones((4,4)),dtype=np.int64)
np.asarray(A)[1][3]=14
np.asarray(A)[3][3]=16
print(A)

[[ 1  1  1  1]
 [ 1  1  1 14]
 [ 1  1  1  1]
 [ 1  1  1 16]]


In [2]:
# array() -- Particular
# Numpy.arrange(start,end,step)
# start - value
# end - value
# step - Gap between one value to another value

import numpy as np 
np.arange(1,10)


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.arange(1,100,9)

array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

In [10]:
print(np.arange(2,20,2))
np.arange(1,25,2)


[ 2  4  6  8 10 12 14 16 18]


array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [11]:
a1=np.array([(1,2,3),(4,5,6)])
print("First row= ",a1[0])


First row=  [1 2 3]


In [12]:
a1=np.array([(1,2,3),(4,5,6)])
print("Second row= ",a1[1])

Second row=  [4 5 6]


In [13]:
a1=np.array([(1,2,3),(4,5,6)])
print("slicing column= ",a1[:,1])

slicing column=  [2 5]


In [14]:
a1=np.array([(1,2,3),(4,5,6)])
print("slicing  last column= ",a1[:,2])

slicing  last column=  [3 6]


In [15]:
a1=np.array([(1,2,3),(4,5,6)])
print("Row and column= ",a1[1,:1])

Row and column=  [4]


In [16]:
a1=np.array([(1,2,3),(4,5,6)])
print("Second row second column= ",a1[1][1])

Second row second column=  5


In [19]:
a1=np.random.normal(5,1,10)
print(a1)

[3.803571   3.56964695 4.79626764 3.25941339 4.93365276 3.51428868
 6.31908565 4.3446787  5.85887692 4.63350818]


In [21]:
a1=np.random.normal(5,1,10)
print(a1)
print("min value= ",np.min(a1))
print("max value= ",np.max(a1))
print("median value= ",np.median(a1))

[4.92309142 4.13014059 2.79209663 4.05584546 5.71186953 5.58607866
 4.12933124 5.61505725 6.00596101 5.34337024]
min value=  2.792096627346654
max value=  6.00596101449789
median value=  5.133230830581823


In [22]:
# Multiple of 1d array
# numpy.dot(x,y)

c1=np.array([1,2])
c2=np.array([4,5])
np.dot(c1,c2)

14

In [25]:
c1=np.array([(1,2),(3,4)])
c2=np.array([(3,4),(1,2)])
np.dot(c1,c2)

array([[ 5,  8],
       [13, 20]])

#### Pandas Basics
* Python is one of the popular programming language for data analysis <br>
* Python is offering the lib called pandas used for importing and analyzing pretty muchfaster and easy 
Pandas DataFrames
  * Data Analysis with Python   

In [35]:
import pandas as pd
dict={"Name":["Anil","Akhil","Dinesh","Harsha"],"Email":["anil@gmail.com","akhil@gmail.com","Dinesh@gmail.com","Harsha@gmail.com"],"Number":["987","999","444","888"],"Address":["hyd","hyd","hyd","hyd"]}
b=pd.DataFrame(dict)
print(b)

     Name             Email Number Address
0    Anil    anil@gmail.com    987     hyd
1   Akhil   akhil@gmail.com    999     hyd
2  Dinesh  Dinesh@gmail.com    444     hyd
3  Harsha  Harsha@gmail.com    888     hyd


In [37]:
b.index =["01","02","03","04"]
print(b)

      Name             Email Number Address
01    Anil    anil@gmail.com    987     hyd
02   Akhil   akhil@gmail.com    999     hyd
03  Dinesh  Dinesh@gmail.com    444     hyd
04  Harsha  Harsha@gmail.com    888     hyd


In [40]:
# supermarket.csv-Analysis(which product is having higher selling %)
# which product is having least selling %
import pandas as pd
products=pd.read_csv('Filename.csv')
print(products)

FileNotFoundError: [Errno 2] File b'Filename.csv' does not exist: b'Filename.csv'